{{- if .Values.config.appBaseLayoutConfigKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-cms.appBaseLayoutConfigKeySecretName" . }}
type: Opaque
data:
  appBaseLayoutConfigKey: {{ .Values.config.appBaseLayoutConfigKey | b64enc }}

---
{{- end }}
{{- if .Values.config.appApiUrl }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-cms.appApiUrlSecretName" . }}
type: Opaque
data:
  appApiUrl: {{ .Values.config.appApiUrl | b64enc }}

---
{{- end }}
{{- if .Values.config.appWebUrl }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-cms.appWebUrlSecretName" . }}
type: Opaque
data:
  appWebUrl: {{ .Values.config.appWebUrl | b64enc }}
{{- end }}
