{{- if .Values.config.apiKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-cms.apiKeySecretName" . }}
type: Opaque
data:
  apiKey: {{ .Values.config.apiKey | b64enc }}

---
{{- end }}
{{- if and .Values.config.admin.email .Values.config.admin.password }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-cms.adminSecretName" . }}
type: Opaque
data:
  email: {{ .Values.config.admin.email | b64enc }}
  password: {{ .Values.config.admin.password | b64enc }}

{{- end }}
