apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "myriad-db.fullname" . }}
  labels:
    {{- include "myriad-db.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ include "myriad-db.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "myriad-db.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
