apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "myriad-db.fullname" . }}
  labels:
    {{- include "myriad-db.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["deployments"]
    verbs: ["list", "watch"]
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get","list", "watch"]
