apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-db.fullname" . }}-headless
  labels:
    {{- include "myriad-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: mongo
  clusterIP: None
  selector:
    {{- include "myriad-db.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-db.fullname" . }}
  labels:
    {{- include "myriad-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: mongo
  selector:
    {{- include "myriad-db.selectorLabels" . | nindent 4 }}
